### ISSUE TITLE
Include TestBench

### ISSUE THREAD

**Issue by MatheusRich** [MichaelSp/rspec_vs_minitest_vs_cucumber#2]
I think this is an interesting alternative too: http://test-bench.software/

**Comment by MatheusRich** [comment]
Nice! Should we update the Readme as well with the results?

**Comment by MichaelSp** [comment]
Sure, no results yet however .... https://github.com/MichaelSp/rspec_vs_minitest_vs_cucumber/actions/runs/565927952

**Comment by MichaelSp** [comment]
There you go: https://github.com/MichaelSp/rspec_vs_minitest_vs_cucumber
